### PR TITLE
[fix #8] create nucleus-stage deployment in frankfurt AWS

### LINKED ISSUE #8: Create nucleus-stage deployment in frankfurt
- Depends on #7 
- port from https://github.com/mozmeao/nucleus-config/blob/master/frankfurt/nucleus-dev/deploy.yaml

### PR DESCRIPTION
**Pull request by jpetto**

### CODE REVIEW

**Comment by jpetto** [comment]
@jgmize Essentially copy pasta'd `frankfurt/nucleus-dev/deploy.yaml` and did a find/replace on `nucleus-dev`. (Also removed [a DEIS config](https://github.com/mozmeao/nucleus-config/blob/master/frankfurt/nucleus-dev/deploy.yaml#L40-L41) that I assume we don't need.)

I'm not sure about resourcing for stage - do we need more than one replica here? If so, would we also need to change the `rollingUpdate` section?

Lastly, is this blocked on getting secrets in?

**Comment by jgmize** [comment]
> (Also removed a DEIS config that I assume we don't need.)

We should update the [HostnameMiddleware that uses DEIS_APP](https://github.com/mozilla/nucleus/blob/80195d10ca2d7abae44d86d3949b3cb4a6bae956/nucleus/base/middleware.py#L8)

> I'm not sure about resourcing for stage - do we need more than one replica here? 

I think it makes sense to increase stage replicas to 2

> If so, would we also need to change the rollingUpdate section?

It's not necessary, but we could increase the `maxSurge` in that section to 2 for slightly quicker deployments.

> Lastly, is this blocked on getting secrets in?

Yes, `nucleus-stage-secrets` needs to exist in the `nucleus-stage` namespace and it needs to have each of the values [referenced in the deployment](https://github.com/mozmeao/nucleus-config/pull/13/files#diff-aff2f9849f8c599f374e51aad72e2acfR36) before the deployment will work.

**Comment by jgmize** [comment]
The secrets described in https://github.com/mozmeao/nucleus-config/pull/13#issuecomment-494379936 have been created so the deploy is unblocked.

**Review by jgmize — APPROVED** [review]
This looks like a great start. Let's deploy this and iterate.

**Pull request merged**
