### PR TITLE
Add initial version of deploy.py

### PR DESCRIPTION
**Pull request by jgmize**
Poll `kubectl rollout status` until deployment complete

### CODE REVIEW

**Review by jpetto — APPROVED** [review]
LGTM! :shipit:

**Comment by jgmize** [comment]
I forgot that yaml is not in the standard library, so this [fails](https://gitlab.com/mozmeao/nucleus-config/-/jobs/204541486) at the `import yaml` on the gitlab runner.

**Comment by jpetto** [comment]
Do we need to update the Ansible script to install the yaml package?

**Comment by jgmize** [comment]
My original reasons for using a python script are obsoleted by recent enhancements to kubectl. I'm going to close this out in favor of the approach in https://github.com/mozmeao/nucleus-config/pull/5/files#diff-96edf7a6f008de9e928d04e1ae5e12a5R9

**Pull request closed without merging**
