### PR TITLE
Switch the nucleus services to use tcp for backend communications

### PR DESCRIPTION
**Pull request by duallain**
Through experimentation it seemed like tcp/ssl as
instance/backend protocol seemed to fix the truncation
of large files.  This change is to switch nucleus to that setup.

### CODE REVIEW

**Comment by pmac** [comment]
That means basically exposing gunicorn directly to the world though, which doesn't tend to work out that well. Will we also need some sort of HTTP proxy?

**Comment by duallain** [comment]
We could use the nginx ingress controller, was choosing between that and this change.  Went with this one because the work to do it was so much less.

I'm not sure how much different the elb would behave in layer 7 vs layer 4 mode.  Tried looking around for information on gunicorn + elbs + eks and I'm not turning up a whole lot.  My networking knowledge is pretty limited, and if you've tried something like this before and it didn't work that's fine (adding nginx isn't too bad). I don't think that we're changing the connection model very much by changing the listeners, but https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-listener-config.html doesn't really address how much work the elb does for you in layer 7 mode (it just talks about stickiness/headers).

**Comment by pmac** [comment]
Cool. I'm +1 on us giving it a shot 👍

**Comment by duallain** [comment]
@pmac haven't tested the prod portion of this updated pr, but dev is live at `nucleus.dev.fr.moz.works.` for testing. (This is mostly just a bump to get github to show the pr to you)

**Review by limed — APPROVED** [review]
r+

**Pull request merged**
